In [7]:
import numpy as np

arr = np.array([2,6,3,7,37,74,9])
print(np.sort(arr))


[ 2  3  6  7  9 37 74]


In [10]:
arr.sort()
print(arr)


# np.sort(arr) → Function → Returns new array (original unchanged)

# arr.sort() → Method → Modifies array in-place (original changed)

[ 2  3  6  7  9 37 74]


In [13]:
# Concatinating two arrays

a = np.array([3,46,23,65])
b = np.array([4, 56,75,80])
c = np.array([4, 56,75,80])

print(np.concatenate([a,b,c])) # we have to pass a,b in form of iterable either list or tuple

[ 3 46 23 65  4 56 75 80  4 56 75 80]


In [20]:
print(np.sort(np.concatenate([a,b,c])))

[ 3  4  4 23 46 56 56 65 75 75 80 80]


In [24]:
# if array are of different dimensions
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[7,8,9]])
print(np.concatenate([x,y]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
# Using axis parameter explicitly
print(np.concatenate([x, y], axis=0))  # Same as default

# Using vstack (vertical stack)
print(np.vstack([x, y]))

# Using r_ (concatenation shortcut)
print(np.r_[x, y])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
z = np.array([[7,8,9],[0,0,0]])
# Using axis parameter explicitly axis =1
print(np.concatenate([x, z], axis =1)) 

[[1 2 3 7 8 9]
 [4 5 6 0 0 0]]


In [38]:
# Reshaping the arrays 

# 2D
arr = np.arange(12)
print(arr)
print(arr.reshape(6,2))
print(arr.reshape(2,6))
print(arr.reshape(2,2,3))



[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [42]:
# 3D
arr = np.arange(27)
print(arr)
x= arr.reshape(3,3,3)
print(x)
print(x.reshape(-1)) # converts back to 1 D array
# or
print(x.reshape(27))




[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
